version: '3.4'

services:
  node:
    env_file:
    - .env
    build:
      context: ./
      target: development
    image: aws-lambda-typescript-nodejs-12:12.13.0-alpine
    working_dir: /app
    command: yarn run start:dev:docker
    networks:
      - web
    volumes:
      - ./:/app

    ports:
      - "3108:4000"
      - "9108:9229"

networks:
  web:

